### ISSUE TITLE
Most routes don't work when deployed on cluster

### ISSUE THREAD

**Issue by rlleshi** [SeldonIO/MLServer#1006]
Deployed some models on a cluster as per the instructions [here](https://docs.seldon.io/projects/seldon-core/en/latest/install/aws.html?#install-cluster-ingress). However, the only root that works is the inference root: `https://<hostname>/seldon/<namespace>/<deployment>/v2/{model}/model/infer`

Others are throwing 500 errors:

- `models/{model}/ready`
- `repository/index`
- `models/{model}`

**Comment by adriangonz** [comment]
Hey @rlleshi ,

This is more of a Seldon Core question - rather than a MLServer one.

Seldon Core runs with an executor sidecar in front of your model, which only forwards the `/infer` routes. If you want access to the rest of routes, then you can disable the executor. You should be able to find instructions on how to do that in the SC docs:

https://docs.seldon.io/projects/seldon-core/en/latest/graph/svcorch.html#bypass-service-orchestrator-version-0-5-0
