### ISSUE TITLE
warm_workers seems not to be working

### ISSUE THREAD

**Issue by rlleshi** [SeldonIO/MLServer#1231]
My assumption was (not entirely clear from the [docs](https://mlserver.readthedocs.io/en/latest/reference/model-settings.html#mlserver.settings.ModelSettings.warm_workers)) that enabling this would reduce the latency of the first few requests that are sent to the model since the model has already been initialized.

However, the overall inference time does not seem to change regardless of whether `warm_workers` is set to `True` or not. There's still some latency with the initial requests. I've also enabled `load_models_at_startup`.

**Comment by adriangonz** [comment]
Hey @rlleshi ,

The `warm_workers` option is now deprecated. This was required previously when workers were scaled "lazily". However,  all workers are now ready from the start with all models loaded. 

Since the models are already loaded when MLServer comes up, it's unclear why latency would be high at start. There are cases where ML frameworks wait to initialise certain things until the model starts performing inference. In that case, the workaround would be to send a few requests during startup, which is something discussed in #985. 

Given we've got a diff issue to track that, I'll close this for now but feel free to continue the discussion in #985.

**Comment by rlleshi** [comment]
@adriangonz could be useful to update [the docs](https://mlserver.readthedocs.io/en/latest/reference/model-settings.html#mlserver.settings.ModelSettings.warm_workers)

**Comment by adriangonz** [comment]
Good point @rlleshi, it's unclear why that's not picking up the deprecated flag. We'll have a look.
