### ISSUE TITLE
How can i load model from s3, minio or gs storage through uri?

### ISSUE THREAD

**Issue by whoisltd** [SeldonIO/MLServer#1343]
I went through the document on the website, but I couldn't find any information regarding loading a model from s3, minio or gs through uri with ML Server. Would you happen to have any help or support regarding this issue?

**Comment by agrski** [comment]
Hi @whoisltd,

Knowing the protocols for various blob storage technologies is a large amount of code overhead that's not the focus of what MLServer provides.

Within Seldon, for example in Seldon Core, it's common to use a tool like Rclone to handle this instead.  This reduces the inherent complexity of projects like MLServer and maintains a nice abstraction -- one tool handles remote storage, others can work off the basis of local storage.

The slight caveat to this is that certain ML runtimes _do_ know about particular stores, such as Hugging Face and its model hub.  That's built into the runtime, rather than MLServer itself.  Also, for storage types not supported by Rclone or similar tools, it's always possible to write that integration into your own, custom runtime and reuse that across your models.
