### ISSUE TITLE
multiple inputs support

### ISSUE THREAD

**Issue by lianxmfor** [SeldonIO/MLServer#304]
I found in the mlserver code that mlserver does not support multiple inputs, but the model does. I wonder if there is any consideration for this?

Are there any plans to support it in the future?

mlserver: https://github.com/SeldonIO/MLServer/blob/0936e26354a6df77c7692faaa9c9467f5f674573/runtimes/lightgbm/mlserver_lightgbm/lightgbm.py#L46

sklearn: https://github.com/SeldonIO/MLServer/blob/0936e26354a6df77c7692faaa9c9467f5f674573/runtimes/sklearn/mlserver_sklearn/sklearn.py#L58

xgboost:
https://github.com/SeldonIO/MLServer/blob/0936e26354a6df77c7692faaa9c9467f5f674573/runtimes/xgboost/mlserver_xgboost/xgboost.py#L46

...

**Comment by adriangonz** [comment]
Hey @lianxmfor, 

Following our conversation on the community Slack, glad that you managed to make it work!

Just for completeness, in case someone else also stumbles on this one, multiple input tensors should be part of the same input entry in the MLServer payload. E.g. let's say you have a `1 x 4` tensor, where `1` is the "batch" dimension. Your input payload combining `N` different entries should be a single tensor with shape `N x 4`, rather than 4 separate entries.

For extra context, each element on the inputs array is considered as a separate "input head" - i.e. a separate parameter to the model.
