### ISSUE TITLE
Compress requests / responses

### ISSUE THREAD

**Issue by axsaucedo** [SeldonIO/MLServer#319]
Leverage `gzip` to compress requests / responses.

**Comment by agrski** [comment]
I'd be cautious about how this is implemented - for small payloads, the compression/decompression time might be a more significant cost than the network's speed.
Also for small payloads or ones without much repetition in their content, the compressed size might be larger than its uncompressed equivalent because of the dictionary's overheads.

There are probably some heuristics about what dictionary size to use and when to apply compression.
