### ISSUE TITLE
Correct approach to JSON request / response tensor data

### ISSUE THREAD

**Issue by iamahern** [SeldonIO/MLServer#396]
I have a legacy model with an existing JSON serialization I am attempting to wrap in MLServe.  Looking at the docs it appears as the intended approach is to use `JSON.dumps()/.loads()` and stuff it as a string / BYTES data.  I have tested and that does work using the REST server, but I could not find anything in the docs to validate that this is the intended usage

In ticket #342, streamlining this use case was called out, but I could not find a corresponding example in the code base.

Questions:
1. Correct approach to handling JSON request response is `JSON.dumps()/.loads()` then stuff it in as BYTES, possibly with content_type hints?
2. Would it be possible for you to include an example where the a custom model `predict()` takes JSON input / output? This is a fairly common use case and will help a lot of teams bootstrap themselves with MLServe before (if possible) moving to a more optimized / tabular format for the data inputs.

**Comment by adriangonz** [comment]
Hey @iamahern , 

That's a very good point. 

At the moment, stuffing it as `BYTES` is the way to go. On top of this, you can also set the content type to `str`, so that MLServer knows that it's a string. Although, when using the REST API this will always be implicitly the case (not so with gRPC). 

Something that we've got on the list is adding a new section to the docs on encoding / decoding common payloads (e.g. tensor, dataframe, image, JSON, etc.) to and from the V2 protocol. Do you think something like this could be useful? Additionally, something else we've been thinking about is extending the current codec functionality to also provide logic to encode a payload to  the V2 protocol (e.g. doing something like `JSONCodec.encode_to_request(my_json_payload)`), which could help ease some of these pain points on the client side.

It would be great to hear your thoughts on both points above!

**Comment by iamahern** [comment]
Thanks @adriangonz for the quick response. So this answers the first of my questions/points. 

For your ideas, I think both the encoding/decoding commons payloads documents and a set of prebuilt codec helpers would be extremely helpful. I would regard the docs as more important as that will be the first point of contact for teams trying to test/adopt MLServer. Once you understand the encoding conceptually, most of the codecs are fairly simple for teams to write themselves.

**Comment by iamahern** [comment]
@adriangonz - created https://github.com/SeldonIO/MLServer/pull/402 to resolve this ticket.

**Comment by iamahern** [comment]
Resolving based on #402
