### ISSUE TITLE
[Bug] ImportError: cannot import name 'Schema' from 'pydantic'

### ISSUE THREAD

**Issue by pbarker** [SeldonIO/MLServer#517]
On a fresh install using Poetry, `poetry add mlserver` it installs at `1.0.1`

Then running `poetry run mlserver start .` errors in:

```
  File "/Users/pbarker/ghq/github.com/onemedical/ml-research/infra/inference/seldon/xgb/.venv/lib/python3.8/site-packages/fastapi/params.py", line 4, in <module>
    from pydantic import Schema
ImportError: cannot import name 'Schema' from 'pydantic'
```

Related to https://github.com/SeldonIO/MLServer/issues/139

**Comment by adriangonz** [comment]
Hey @pbarker , 

I just tried with a fresh environment using `pip` and I wasn't able to replicate the above. Could you share the version of FastAPI and Pydantic that you're currently running? Not an expert in Poetry, but is there any chance that some subdeps are missing in the underlying Poetry env? Or that it's pulling some deps from a diff environment upstream?

**Comment by adriangonz** [comment]
Just as a follow up to the above, I just tried the same thing with a fresh Poetry environment, and was able to replicate what you reported initially. Not sure what could be causing this mismatch between `pip` + `virtualenv` and Poetry though...

**Comment by RafalSkolasinski** [comment]
@pbarker please provide version of `poetry` and `python` that you are using

**Comment by adriangonz** [comment]
Hey @pbarker ,

After looking a bit more into this one, it seems that the issue is caused by Poetry choosing a really old version of FastAPI to satisfy the direct MLServer dependency. As a temporary workaround, could you try running the command below? This should ensure that the latest version of FastAPI is used instead. 

```
poetry add fastapi
```

In the meantime, we'll try to dig a bit more into what's triggering that behaviour from Poetry, as well as potentially pinning our `fastapi` dependency to a version range to force Poetry to install a newer version. We'll keep this issue opened until that's sorted out.

**Comment by pbarker** [comment]
Hey @adriangonz 

```
poetry add fastapi
```

Works! Thanks. https://github.com/SeldonIO/MLServer/issues/139 seems fairly important to tackle soon

**Comment by RafalSkolasinski** [comment]
The https://github.com/SeldonIO/MLServer/issues/139  won't really help this use case here. Having the `poetry.lock` file will only make sure that if you do `poetry install` it would use the locked versions. So it will help to keep the image environments pinned but will not affect how `poetry add mlserver` works.
