### ISSUE TITLE
Model URI isn't a URI

### ISSUE THREAD

**Issue by pbarker** [SeldonIO/MLServer#526]
In `model-settings.json` the `uri` parameter isn't a URI but a filepath. A URI refers to a web resource, this gives a false impression.

**Comment by adriangonz** [comment]
Hey @pbarker ,

While it's true that MLServer won't handle the artifact download itself, a URI can also be used to refer to a local file (e.g. `file://....` URIs). Given that the usage is not incorrect, perhaps this should be more a question of clarifying this point on the docs?

**Comment by adriangonz** [comment]
Hey @pbarker ,

Your intuition is correct. Just to confirm on the above, MLServer won't download web resources. This is delegated to upstream serving engines like Seldon Core or KServe (which will handle this download at the infrastructure level, through the use of init containers in K8s). The main reason is that downloading any external artefact within the model container can lead to timeouts within K8s (as well as taking a long time to come up). 

You're right in that, when running MLServer outside of any of these serving engines (and / or locally), it could be useful to download these artifacts within the MLServer process itself. However, this use case is not currently prioritised atm.

**Comment by pbarker** [comment]
okay interesting @adriangonz, thanks for the input, that clarified a couple things but I'm still a bit confused on one part:

If mlserver is taking the stance that it won't download models, then why the URI parameter? URI is a term for web resources, and if I supply an `s3` path there I get an error when calling `get_model_uri`. If it is only ever expecting local files then wouldn't `filepath` or the likes make that more clear?

**Comment by pbarker** [comment]
also:

> which will handle this download at the infrastructure level, through the use of init containers in K8s

are there any examples of this anywhere? I only see examples where the model is directly loaded out of the container

**Comment by adriangonz** [comment]
Hey @pbarker ,

Actually, a URI can also be used to identify local resources, like a file in the local filesystem. Usually, this is done more explicitly using the `file://` schema (which perhaps would make things clearer in this case?). In the future, we may also allow users to point to other kind of resources (e.g. other models running within MLServer, which could make sense for explainers). That's why we are keen on keeping the field name generic. 

On the point about init containers, that should be the default behaviour with Seldon Core when using a `SeldonDeployment` and a "pre-packaged server". You can read more about it on the SC docs:

https://docs.seldon.io/projects/seldon-core/en/latest/servers/overview.html#init-containers

For KServe, they do something similar, although not from an init container. Instead, they download the artifacts through a sidecar "puller" container:

https://kserve.github.io/website/0.8/modelserving/mms/modelmesh/overview/#learn-more

**Comment by pbarker** [comment]
Thanks for the feedback @adriangonz 

>  In the future, we may also allow users to point to other kind of resources

This would make sense to me, I guess my main gripe is that currently it prevents passing anything other than a local file and it isn't commonplace to call a local file a URI, especially since every other serving tool takes a URI that accepts web resources. As my team of 5 has been evaluating seldon/kserve, every single person has been confused by this.

It could perhaps be solved by better docs and examples. One of the most common use cases is wanting to download a model from S3 and load it into a custom server. We have struggled to understand how thats implemented with mlserver.

> On the point about init containers, that should be the default behaviour with Seldon Core when using a SeldonDeployment and a "pre-packaged server". You can read more about it on the SC docs:

Thanks for providing these docs, it would be great if there was one example where a model is pulled from s3/gs and loaded into the mlserver, this is very hard to grok.

**Comment by adriangonz** [comment]
Hey @pbarker ,

Doing some cleaning so, since this questions seems mostly answered, I'll be closing down this ticket. Although, feel free to reopen if there are still any other outstanding points.
