### ISSUE TITLE
Additional Uvicorn configuration

### ISSUE THREAD

**Issue by erik-hasse** [SeldonIO/MLServer#571]
Is there any way to set additional Uvicorn configuration? Setting variables starting with`UVICORN_` as indicated in the [Uvicorn docs](https://www.uvicorn.org/settings/) doesn't work with `uvicorn.Server().serve()` since the variables are [read with click](https://github.com/encode/uvicorn/blob/6286ecc398f8e3c368ba945c2f481cfba36ca0f8/uvicorn/main.py#L53) as part of `uvicorn.run`.

If nothing is available, I could open a PR adding something like this to `mlserver.rest.RESTSever.start`:
```python
UVICORN_ENV_PREFIX = 'UVICORN_'

uvicorn_options = {
    key.lower()[len(UVICORN_ENV_PREFIX):]: val
    for key, val in os.environ.items() if key.upper().startswith(UVICORN_ENV_PREFIX)
}
cfg = uvicorn.Config(
    self._app,
    host=self._settings.host,
    port=self._settings.http_port,
    log_config=self._settings.logging_settings,
    **uvicorn_options,
)
```

**Comment by adriangonz** [comment]
Hey @erik-hasse ,

That's a great point.

It would be really useful to learn more about what Uvicorn settings you're missing, as it may make sense to make some of those high-level config fields for MLServer (or even default values).

**Comment by erik-hasse** [comment]
The main thing I need right now is `root-path`, but more flexibility is good. This one can also be set as part of FastAPI app creation, so more configuration there would work instead.

**Comment by adriangonz** [comment]
Hey @erik-hasse ,

Thanks for providing that context. 

In that case, would it make sense to expose the `root_path` property directly, rather than forwarding all uvicorn fields? I'd be keen to try and keep the config interface as simple as possible, at least while it makes sense to do so (i.e. if we get to the point where we need to forward 10s of fields down to uvicorn, then we could make the call of just adding a full blown "`uvicorn_config`" field there).

**Comment by erik-hasse** [comment]
Yeah, just adding root_path would fix my issue for now.

My only concern would be that the next time some setting comes up for anyone, they have to open an issue and wait for it to be added, even though Uvicorn/FastAPI already support the setting. It doesn't lead to a great user experience.

**Comment by adriangonz** [comment]
I see your point. My main concern would be that Uvicorn settings which may also apply to other places (e.g. number of workers, which would relevant to the gRPC server as well, or the logging configuration) would get applied only to the REST server. That's why, initially, I was thinking to take this on a setting-by-setting basis. There's an extra added benefit in that approach, in that we would keep the settings interface unified. That is, the `settings.json` file would still be the single point of configuration for MLServer. 

Having said that, I understand it could be frustrating to go through the whole issue / PR process for each new Uvi setting.

Given that this is the first request for extra Uvi config, I'd still go with adding the `root_path` field to the main config, but keeping an eye on new requests of this type. I'd say that by the 2nd or 3rd time someone asks for an extra Uvi-specific setting, it'd would be worth re-thinking the above.
