### ISSUE TITLE
model unload doesn't release memory

### ISSUE THREAD

**Issue by lizzzcai** [SeldonIO/MLServer#986]
Hi MLServer team,

I am testing [KServe ModelMesh](https://github.com/kserve/modelmesh-serving) with MLServer custom runtime, however, I noticed that the memory is not being released after I call the unload endpoint.

## Update
The example is run with `MLSERVER_PARALLEL_WORKERS=1`, however, when I tested with `MLSERVER_PARALLEL_WORKERS=0`, the behaviour is similar.

example (find the repo of the example at the end):
```sh
# launch the mlserver
❯ docker run -it --rm -p 8001:8001 -p 8002:8002 \
  -v $(pwd)/models:/models/_mlserver_models \
  -e MLSERVER_MODEL_NAME=dummy-model-fixme \
  -e MLSERVER_MODELS_DIR=/models \
  -e MLSERVER_DEBUG=true \
  -e MLSERVER_LOAD_MODELS_AT_STARTUP=false \
  lizzzcai/my-custom-mlserver:0.0.6

# check stats
❯ docker stats 235009afac2b --no-stream
CONTAINER ID   NAME             CPU %     MEM USAGE / LIMIT     MEM %     NET I/O     BLOCK I/O    PIDS
235009afac2b   magical_dhawan   0.41%     138.4MiB / 7.773GiB   1.74%     936B / 0B   0B / 283kB   22

# check model repository, no model
❯ curl -i -X POST -H "Content-Type: application/json" "http://localhost:8002/v2/repository/index" -d "{}"

[{"name":"text-classifier","version":"v0.1.0","state":"UNAVAILABLE","reason":""},{"name":"text-translator","version":"v0.1.0","state":"UNAVAILABLE","reason":""}]% 

# load the model
❯ curl -i -X POST -H "Content-Type: application/json" "http://localhost:8002/v2/repository/models/text-translator/load" -d "{}"
HTTP/1.1 200 OK

# check the repository again, text-transtator is ready
❯ curl -i -X POST -H "Content-Type: application/json" "http://localhost:8002/v2/repository/index" -d "{}"

[{"name":"text-classifier","version":"v0.1.0","state":"UNAVAILABLE","reason":""},{"name":"text-translator","version":"v0.1.0","state":"READY","reason":""}]%

# inference
❯ curl -i -X POST -H "Content-Type: application/json" "http://localhost:8002/v2/models/text-translator/infer" -d "{\"inputs\": [{ \"name\": \"text\", \"shape\": [2], \"datatype\": \"BYTES\", \"parameters\": { \"content_type\": \"str\" }, \"data\": [\"My name is Sarah and I live in London\", \"My name is Wolfgang and I live in Berlin\"] }] }"

{"model_name":"text-translator","model_version":"v0.1.0","id":"f627c078-873f-44f2-bae1-e73d9b61c4a1","parameters":{},"outputs":[{"name":"translations","shape":[2],"datatype":"BYTES","parameters":{"content_type":"str"},"data":["Mein Name ist Sarah und ich lebe in London","Mein Name ist Wolfgang und ich lebe in Berlin"]}]}%

# check the stats, memory is increased
❯ docker stats 235009afac2b --no-stream
CONTAINER ID   NAME             CPU %     MEM USAGE / LIMIT     MEM %     NET I/O           BLOCK I/O     PIDS
235009afac2b   magical_dhawan   0.41%     1.577GiB / 7.773GiB   20.29%    3.89kB / 2.57kB   0B / 1.14MB   34

# unload the model
curl -i -X POST -H "Content-Type: application/json" "http://localhost:8002/v2/repository/models/text-translator/unload" -d "{}"
HTTP/1.1 200 OK

# check model repository, text-translator is unavaiable
❯ curl -i -X POST -H "Content-Type: application/json" "http://localhost:8002/v2/repository/index" -d "{}"

[{"name":"text-classifier","version":"v0.1.0","state":"UNAVAILABLE","reason":""},{"name":"text-translator","version":"v0.1.0","state":"UNAVAILABLE","reason":""}]% 

# check the stats, memory drops a bit but is still high than the value at the beginning
❯ docker stats 235009afac2b --no-stream
CONTAINER ID   NAME             CPU %     MEM USAGE / LIMIT     MEM %     NET I/O           BLOCK I/O     PIDS
235009afac2b   magical_dhawan   0.21%     1.062GiB / 7.773GiB   13.66%    5.11kB / 3.57kB   0B / 1.14MB   34
```
If I call loading the same model `multiple` times, the memory will go up to `3.6 GB`, and the memory will stay at 2.7 GB after unload the model
```
# load same model multiple times
❯ curl -i -X POST -H "Content-Type: application/json" "http://localhost:8002/v2/repository/models/text-translator/load" -d "{}"
HTTP/1.1 200 OK
❯ curl -i -X POST -H "Content-Type: application/json" "http://localhost:8002/v2/repository/models/text-translator/load" -d "{}"
HTTP/1.1 200 OK
❯ curl -i -X POST -H "Content-Type: application/json" "http://localhost:8002/v2/repository/models/text-translator/load" -d "{}"
HTTP/1.1 200 OK

❯ docker stats 235009afac2b --no-stream
CONTAINER ID   NAME             CPU %     MEM USAGE / LIMIT     MEM %     NET I/O           BLOCK I/O     PIDS
235009afac2b   magical_dhawan   0.28%     3.673GiB / 7.773GiB   47.26%    7.39kB / 5.22kB   0B / 1.14MB   34

# unload the model
❯ curl -i -X POST -H "Content-Type: application/json" "http://localhost:8002/v2/repository/models/text-translator/unload" -d "{}"
HTTP/1.1 200 OK

❯ docker stats 235009afac2b --no-stream
CONTAINER ID   NAME             CPU %     MEM USAGE / LIMIT     MEM %     NET I/O          BLOCK I/O     PIDS
235009afac2b   magical_dhawan   0.23%     2.737GiB / 7.773GiB   35.22%    8.7kB / 6.11kB   0B / 1.14MB   34
```

I am following the custom inference runtimes [example](https://mlserver.readthedocs.io/en/latest/user-guide/custom.html#writing-a-custom-inference-runtime) and you can find the above example in this [repo](https://github.com/lizzzcai/kserve-modelmesh-demo) if you want to reproduce it.

I want to check:
1. if it is an expected behaviour in mlserver? and if not, how to fix the issue.
2. how to unload is performed in mlserver as user doesn't need to define any `unload` function in this [example](https://mlserver.readthedocs.io/en/latest/user-guide/custom.html#writing-a-custom-inference-runtime). In this case, whether assigning the model to a different name rather than `self._model` will affect the memory release? 

Thanks.

**Comment by MLHafizur** [comment]
I have noticed the same issue.

**Comment by adriangonz** [comment]
Hey @lizzzcai @MLHafizur ,

Thanks a lot for raising this one - and thanks again @lizzzcai for that detailed report. 

We're currently looking into this one. It seems we're able to replicate locally, but it's still unclear where the memory overhead that doesn't get deallocated it's coming from. We'll let you know when we know more about this one.

**Comment by sakoush** [comment]
Hello @lizzzcai,

Many thanks for the detailed report about the memory issue you are facing with `MLServer` custom model.

Having looked at the issue in more detailed, we think that the memory not being released on unload is being held by the `torch` backend of the `transformers` library that is used in  `MyTranslatorModel`. Unfortunately at this stage we have no control over memory management of these libraries. There are different discussions on related issues to the one you observed, e.g. [clearing gpu-memory](https://discuss.huggingface.co/t/clear-gpu-memory-of-transformers-pipeline/18310/2)  (we could not find one explicitly for cpu memory). We think that memory will not be released in full unless the process exits.

At couple of considerations though to answer some of the questions raised:

- Model "unload" is done by `MLServer`, check [here](https://github.com/SeldonIO/MLServer/blob/1894ca3164c64f9bbafca5ddc11060f0a21b9253/mlserver/registry.py#L184). The main logic is to dereference the `MLModel` object and by extension any underlying objects (e.g. `self._model`) so that memory is released from the heap at the python level. 
- We are considering to add an explicit `unload` api but we don't think it will resolve your particular issue.
- Calling load on a loaded model acts as a way to refresh the model in `MLServer`. So we load the "new" model before unload the "old" model, which requires extra memory. Although memory is increasing on successive `reload`, at some point it will stabilise and memory will be recycled based on our observations (which is also related to how libraries deal with memory internally). 
- We observed that while different backends might not explicitly release memory on unload. Loading a new model to the same backend will likely reuse memory as opposed to new memory being allocated. 
- We could consider in the future having short-lived processes to deal with this kind of memory issues. This can be done in your custom model but requires that you managed these processes currently.

Please let us know if you have further questions or comments.

**Comment by sakoush** [comment]
@lizzzcai I will close the ticket for now. Please feel free to reach out if you require further clarifications.

**Comment by lizzzcai** [comment]
Hi @sakoush, thanks for your detailed reply. If there are new questions, I will open an issue, thanks for the support!

**Comment by ericlu88** [comment]
Thanks, @sakoush any rough estimate on the timeline? This is currently a blocker for us since our heterogeneous models load/unload frequently on the cluster.

**Comment by adriangonz** [comment]
Hey @ericlu88 , 

This is something currently planned for the next release of MLServer (i.e. `1.4.0`). You can keep track of the status on the issue to add support for the `unload()` method:

https://github.com/SeldonIO/MLServer/issues/1145

**Comment by ericlu88** [comment]
@adriangonz awesome, thanks for the update, will subscribe and try it out first when it's released.

**Comment by adriangonz** [comment]
In the meantime @ericlu88, it should also be possible to set the `PYTORCH_NO_CUDA_MEMORY_CACHING=1` env var to disable the GPU "allocation cache" used by PyTorch (AFAIK that should have the same effect as `torch.cuda.empty_cache()`):

https://pytorch.org/docs/stable/notes/cuda.html#cuda-memory-management

**Comment by ericlu88** [comment]
oh awesome let us experiment with it, thanks for sharing the pointer!
